# Generated by Django 5.2.7 on 2025-10-11 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safaris', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='safaripackage',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('safari', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='safaris.safaripackage')),
            ],
        ),
    ]
